version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ~/eco/eco-server/certificate.pem:/etc/cert/certificate.pem
          - ~/eco/eco-server/key.pem:/etc/cert/key.pem
